// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';

import * as MediaRouteRoute from '@/app/browse/[mediaType]/[id]/page.info';
import * as BrowseRouteRoute from '@/app/browse/page.info';
import * as MoviesRouteRoute from '@/app/movies/page.info';
import * as SearchRouteRoute from '@/app/search/page.info';
import * as TvRouteRoute from '@/app/tv/page.info';

import { makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

export const BrowseRoute = makeRoute('/browse', {
  ...defaultInfo,
  ...BrowseRouteRoute.Route,
});
export const MediaRoute = makeRoute('/browse/[mediaType]/[id]', {
  ...defaultInfo,
  ...MediaRouteRoute.Route,
});
export const MoviesRoute = makeRoute('/movies', {
  ...defaultInfo,
  ...MoviesRouteRoute.Route,
});
export const SearchRoute = makeRoute('/search-input', {
  ...defaultInfo,
  ...SearchRouteRoute.Route,
});
export const TvRoute = makeRoute('/tv', {
  ...defaultInfo,
  ...TvRouteRoute.Route,
});
