// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/(home)/home/page.info";
import * as HomeMediaRoute from "@/app/(home)/home/[mediaType]/[id]/page.info";
import * as MovieModalRoute from "@/app/(movies)/movie/[id]/page.info";
import * as MoviesRoute from "@/app/(movies)/movies/page.info";
import * as TvRoute from "@/app/(tv)/tv/page.info";
import * as TvModalRoute from "@/app/(tv)/tv/[id]/page.info";
import * as ApiSearchRoute from "@/app/api/search/route.info";
import * as SearchRouteRoute from "@/app/search/page.info";

export const Home = makeRoute(
  "/(home)/home",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const HomeMedia = makeRoute(
  "/(home)/home/[mediaType]/[id]",
  {
    ...defaultInfo,
    ...HomeMediaRoute.Route
  }
);
export const MovieModal = makeRoute(
  "/(movies)/movie/[id]",
  {
    ...defaultInfo,
    ...MovieModalRoute.Route
  }
);
export const Movies = makeRoute(
  "/(movies)/movies",
  {
    ...defaultInfo,
    ...MoviesRoute.Route
  }
);
export const Tv = makeRoute(
  "/(tv)/tv",
  {
    ...defaultInfo,
    ...TvRoute.Route
  }
);
export const TvModal = makeRoute(
  "/(tv)/tv/[id]",
  {
    ...defaultInfo,
    ...TvModalRoute.Route
  }
);
export const SearchRoute = makeRoute(
  "/search",
  {
    ...defaultInfo,
    ...SearchRouteRoute.Route
  }
);

export const getApiSearch = makeGetRoute(
  "/api/search",
  {
    ...defaultInfo,
    ...ApiSearchRoute.Route
  },
  ApiSearchRoute.GET
);
