// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';

import * as ErrorPageRoute from '@/app/(pages)/error/page.info';
import * as HomeRoute from '@/app/(pages)/home/page.info';
import * as MoviesRoute from '@/app/(pages)/movies/page.info';
import * as SearchRoute from '@/app/(pages)/search/page.info';
import * as TvRoute from '@/app/(pages)/tv/page.info';
import * as MediaModalRoute from '@/app/@modal/[...slug]/page.info';
import * as ApiSearchRoute from '@/app/api/search/route.info';

import { makeGetRoute, makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

export const ErrorPage = makeRoute('/error', {
  ...defaultInfo,
  ...ErrorPageRoute.Route,
});
export const Home = makeRoute('/home', {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Movies = makeRoute('/movies', {
  ...defaultInfo,
  ...MoviesRoute.Route,
});
export const Search = makeRoute('/search', {
  ...defaultInfo,
  ...SearchRoute.Route,
});
export const Tv = makeRoute('/tv', {
  ...defaultInfo,
  ...TvRoute.Route,
});
export const MediaModal = makeRoute('/[...slug]', {
  ...defaultInfo,
  ...MediaModalRoute.Route,
});

export const getApiSearch = makeGetRoute(
  '/api/search',
  {
    ...defaultInfo,
    ...ApiSearchRoute.Route,
  },
  ApiSearchRoute.GET
);
